site_name: AuditEngine Docs
site_url: https://auditengine.org/
nav:
    - Home: index.md
    - Exporting Guide: exporting_guide.md
    - Uploading Guide: uploading_guide.md
    - How you can help: you_can_help.md
    - Configuration Files: configuration_files.md
    - About: about.md
theme:
  name: material
  #custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
