site_name: AuditEngine Docs
site_url: https://auditengine.org/
nav:
    - Home: index.md
    - User Guide:
        - Overview: user-guide/index.md
        - Exporting Guide: user-guide/exporting_guide.md
        - Uploading Guide: user-guide/uploading_guide.md
        - Configuration Files: user-guide/configuration_files.md
    - Community:
        - How you can help: community/you_can_help.md
        - Donate: community/donate.md
    - Audit Results:
        - Case study: audit-results/case_study.md
    - About:
        - About Us: about/about.md
theme:
  name: material
  #custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
